export const PIN_FILE_TO_PINATA_REQUEST = 'PIN_FILE_TO_PINATA_REQUEST';
export const PIN_FILE_TO_PINATA_SUCCESS = 'PIN_FILE_TO_PINATA_SUCCESS';
export const PIN_FILE_TO_PINATA_FAILED = 'PIN_FILE_TO_PINATA_FAILED';
export const PIN_FILE_TO_PINATA_RESET = 'PIN_FILE_TO_PINATA_RESET';

export const PIN_JSON_TO_PINATA_REQUEST = 'PIN_JSON_TO_PINATA_REQUEST';
export const PIN_JSON_TO_PINATA_SUCCESS = 'PIN_JSON_TO_PINATA_SUCCESS';
export const PIN_JSON_TO_PINATA_FAILED = 'PIN_JSON_TO_PINATA_FAILED';
export const PIN_JSON_TO_PINATA_RESET = 'PIN_JSON_TO_PINATA_RESET';

export const GET_JSON_FROM_PINATA_REQUEST = 'GET_JSON_FROM_PINATA_REQUEST';
export const GET_JSON_FROM_PINATA_SUCCESS = 'GET_JSON_FROM_PINATA_SUCCESS';
export const GET_JSON_FROM_PINATA_FAILED = 'GET_JSON_FROM_PINATA_FAILED';
export const GET_JSON_FROM_PINATA_RESET = 'GET_JSON_FROM_PINATA_RESET';

export const TOKEN_REDUCER_LOADING_TRUE = 'TOKEN_REDUCER_LOADING_TRUE';
export const TOKEN_REDUCER_LOADING_FALSE = 'TOKEN_REDUCER_LOADING_FALSE';





